### ISSUE TITLE
Code Ideas

### ISSUE THREAD

**Issue by Darkere** [Kanzaji/Cat-Downloader-Legacy#4]
Decided to just give an overview of some general issues I see. There is gonna be a lot of stuff that is just my opinion, so feel free to disagree with some. Also there is gonna be a bunch of stuff that you just don't have enough experience for... just keep it in mind for the future :D

# Comments
Comments should be placed when:
- the code does not document itself enough
- you do something unintuitive for whatever reason
- you want java docs (for whatever reason)

### Examples of bad comments: 
https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/CatDownloader.java#L52-L53
https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/CatDownloader.java#L64-L65

### Examples of Good Comments: 
https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/CatDownloader.java#L71-L73

For comments always keep in mind that whenever someone goes and changes something about this code, they will now also have to check each comment for correctness. In less than a year you'll likely not remember enough and this becomes impossible (or really hard work...). Which produces comments that are wrong (which is really bad for hopefully obvious reasons).

# Code Design
Ideal Function size is a highly debated topic with no correct answers. However what most people agree on, is that a single function should not do many things. 

The Main function especially should be tiny, initialising the program to run. Or for a script approach lay out the structure of the program. 

Try to avoid more than 3-5 Indents. It makes it harder to understand the code.

You can put things into functions (or other classes/files) and you can also do something like this `if(!Prerequisite()) return` to reduce complexity

# Questionable Code

https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/CatDownloader.java#L32

Why is this in a static block? Not actually a problem in this case, just a bizarre design. 

---

https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/CatDownloader.java#L95-L96

Avoid duplicate code. If you need to log to both console and log add a function or argument to do so.

---

https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/ArgumentDecoder.java#L47

This entire thing is a bit of a nightmare. Both performance and readability wise. Misnamed Functions, randomly changed control flow... 
Some Pseudo Code for a better approach:
```java
for (String Argument : arguments) {
    if(Argument.StartsWith("-"))
        Argument.RemoveFirstChar
   var Parameter = Argument.SubString(at(":"))
   switch (Parameter) {
        case "WorkingDirectory":
               // Do stuff
        case "SettingsPath"
               //Do Stuff
   }
 }
```
Doing it like this avoids problems like the missing colon here https://github.com/Kanzaji/Cat-Downloader-Legacy/blob/69d5d2ff62ca3cd26377d7afed83cbc0ff0775fc/src/main/java/com/kanzaji/catdownloaderlegacy/ArgumentDecoder.java#L52-L52

No idea if the missing colon causes a problem

**Comment by Darkere** [comment]
Oh... just to make it clear. I don't expect you to fix any of these issues. Just general feedback for whatever you next project is ;)

**Comment by Kanzaji** [comment]
Thanks a lot ❤️
And well, this is my current project I am working on so I will defintiely fix nearly everything in here!

> you want java docs (for whatever reason)

Javadocs is something I definitely like and try to use a lot, but yea random comments for stuff that is self-explanatory are useless at this point, so I'm just gonna go ahead and remove a lot of them 😅

> This entire thing is a bit of a nightmare. Both performance and readability wise. Misnamed Functions, randomly changed control flow...

Well, this was the first thing I did in this app after Logger, and I just was too lazy to actually properly rework it 😅 Thanks for the ideas for a rework ❤️

**Comment by Kanzaji** [comment]
Gonna mark this as completed, as I've reworked I think entire app already with this feedback in mind 😄
Thanks again a lot for the tips :D They did help a lot.
